# Generated by Django 4.1 on 2022-08-28 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener', '0002_alter_link_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='url',
            field=models.CharField(max_length=10000),
        ),
    ]
