# Generated by Django 4.1 on 2022-08-29 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener', '0004_alter_link_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='shorturl',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='url',
            field=models.URLField(max_length=10000, unique=True),
        ),
    ]
