# Generated by Django 4.1 on 2022-08-29 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener', '0005_alter_link_shorturl_alter_link_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='shorturl',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
